url: https://weasels.co
title: kubalasecki
email: kuba@lasica.co
markdown: kramdown
permalink: pretty
encoding: utf-8
text:
  navbar:
    header: 'Łasiczki'
  content:
    block-1-title: 'Transport międzynarodowy'
    block-1: 'Dalekie trasy to nasza specjalność. Nasi kierowcy to doświadczeni pracownicy z wieloletnią praktyką. Stawiamy, na jakość i bezpieczeństwo prowadzonych działań.'
    block-2-title: 'Usługi'
    block-2: 'Jakość i niezawodność jest domeną naszej działalności. Codzienną walkę z czasem przekładamy na zadowolonie klientów i terminowość realizacji zleceń.'
    block-3-title: 'Transport krajowy'
    block-3: 'Codziennie jesteśmy do Państwa dyspozycji, gwarantując, profesjonalne wykonanie powierzonych nam działań. Transport krajowy to dla nas codzienność.'
    made-by: 'łasica'
    copyright: '2016 © Weasels. Wszelkie prawa zastrzeżone.'
  contact:
    michal-tel: '+48 726 922 069'
    michal: 'Michał Łasecki'
    michal-mail: 'michal.lasecki@weasels.co'
    maciej-tel: '+48 727 907 796'
    maciej: 'Maciej Łasecki'
    maciej-mail: 'maciej.lasecki@weasels.co'
  footer:
    name: 'weasels sp. z o. o.'
    about-1: 'Nasza firma transportowa pragnie dostarczyć Państwu pełen zakres usług w zakresie drogowego transportu krajowego i międzynarodowego. Usługi transportowe, spedycja to nasza specjalność, a także pasja! w naszych działaniach jesteśmy niezawodni, ciesząc się uznaniem oraz zaufaniem Klientów w kraju, jak również za granicą. Stawiamy na jakość świadczonych usług!'
    about-2: 'Realizujemy się na wielu płaszczyznach, co daje nam wymierny efekt w postaci konkurencyjnych cen. W zakresie przewozu ładunków taborem ciężarowym na terenie całej Polski, dostarczamy pełną ofertę zarówno w obsłudze logistycznej, jak i spedycyjnej. Realizujemy zamówienia zarówno od dużych Przedsiębiorstw, jak i małych Firm. Dla nas liczy się indywidualne podejście do świadczonych usług. Codziennie jesteśmy dla Państwa! Swoim zasięgiem działania obejmujemy wszystkie kraje Unii Europejskiej.'
    about-3: 'Jesteśmy firmą ceniącą Klienta, dbamy o jakość, terminowość i rzetelność wykonywanych usług transportowych. Ufamy naszym kierowcom. Ich doświadczenie i kwalifikacje sprawiają, że kiedy oni codziennie wyruszają w trasę, my mamy pewność realizacji Państwa zamówienia. Nasi spedytorzy są z nimi w stałym kontakcie, dzięki czemu na bieżąco mogą Państwo śledzić trasę swojej przesyłki. Dbamy o jej bezpieczeństwo, dlatego towar jest ubezpieczony – OC Przewoźnika, tzw. OCP. Jesteśmy firmą transportową posiadającą bardzo bogaty oraz rozbudowany tabor, by świadczone przez nas usługi transportowe, spedycyjne gwarantowały Państwu pełną kompleksowość. Nasza firma również przygotowana jest do przewożenia ładunków niebezpiecznych (ADR).'
    details: 'Dane firmy'
    nip: 'PL 766 199 52 94'
    nip-t: 'NIP:'
    krs: '0000635743'
    krs-t: 'KRS:'
    regon: '365359540'
    regon-t: 'Regon:'
    location: 'ul. Brzozowa 13, 62-100 Wągrowiec, woj. wielkopolskie, Polska'
    location-t: 'Siedziba:'
    spec: 'Transport Drogowy Towarów ( PKD : 49.41.Z )'
    spec-t: 'Działalność:'
    finance: '80.000,00 zł'
    finance-t: 'Kapitał zakładowy'
    email: 'transport@weasels.co'
    court: 'Sąd Rejonowy w Wągrowcu. ul. Kościuszki 18. 62-100 Wągrowiec'
gems:
  - jekyll-haml
